# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: douyin.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List, Optional

import betterproto


@dataclass(eq=False, repr=False)
class PushFrame(betterproto.Message):
    seq_id: int = betterproto.uint64_field(1)
    log_id: int = betterproto.uint64_field(2)
    service: int = betterproto.uint64_field(3)
    method: int = betterproto.uint64_field(4)
    headers_list: List["HeadersList"] = betterproto.message_field(5)
    payload_encoding: str = betterproto.string_field(6)
    payload_type: str = betterproto.string_field(7)
    payload: bytes = betterproto.bytes_field(8)


@dataclass(eq=False, repr=False)
class HeadersList(betterproto.Message):
    key: str = betterproto.string_field(1)
    value: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Response(betterproto.Message):
    messages_list: List["Message"] = betterproto.message_field(1)
    cursor: str = betterproto.string_field(2)
    fetch_interval: int = betterproto.uint64_field(3)
    now: int = betterproto.uint64_field(4)
    internal_ext: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class Message(betterproto.Message):
    method: str = betterproto.string_field(1)
    payload: bytes = betterproto.bytes_field(2)
    msg_id: int = betterproto.int64_field(3)
    msg_type: int = betterproto.int32_field(4)
    offset: int = betterproto.int64_field(5)


@dataclass(eq=False, repr=False)
class ChatMessage(betterproto.Message):
    common: "Common" = betterproto.message_field(1)
    user: "User" = betterproto.message_field(2)
    content: str = betterproto.string_field(3)
    visible_to_sender: bool = betterproto.bool_field(4)
    text_effect: "TextEffect" = betterproto.message_field(5)
    background_image: "Image" = betterproto.message_field(6)
    full_screen_text_color: str = betterproto.string_field(7)
    background_image_v2: "Image" = betterproto.message_field(8)
    public_area_common: "PublicAreaCommon" = betterproto.message_field(9)
    gift_image: "Image" = betterproto.message_field(10)
    agree_msg_id: int = betterproto.uint64_field(11)
    priority_level: int = betterproto.uint32_field(12)
    landscape_area_common: "LandscapeAreaCommon" = betterproto.message_field(13)
    event_time: int = betterproto.uint64_field(14)
    send_gift_during_game: bool = betterproto.bool_field(15)
    send_gift_during_game_msg_id: int = betterproto.uint64_field(16)
    fan_ticket_info: "FanTicketInfo" = betterproto.message_field(17)
    show_type: int = betterproto.int32_field(18)
    color: str = betterproto.string_field(19)
    chat_by: str = betterproto.string_field(20)
    priority: "Priority" = betterproto.message_field(21)


@dataclass(eq=False, repr=False)
class GiftMessage(betterproto.Message):
    common: "Common" = betterproto.message_field(1)
    gift_id: int = betterproto.uint64_field(2)
    group_id: int = betterproto.uint64_field(3)
    repeat_count: int = betterproto.uint64_field(4)
    combo: int = betterproto.uint64_field(5)
    user: "User" = betterproto.message_field(6)
    to_user: "User" = betterproto.message_field(7)
    gift: "Gift" = betterproto.message_field(8)
    describe: str = betterproto.string_field(9)
    priority: "Priority" = betterproto.message_field(10)
    fan_ticket_count: int = betterproto.uint64_field(11)
    event_time: int = betterproto.uint64_field(12)
    batch_info: "BatchInfo" = betterproto.message_field(13)
    gift_group_id: int = betterproto.uint64_field(14)
    send_gift_during_game: bool = betterproto.bool_field(15)


@dataclass(eq=False, repr=False)
class LikeMessage(betterproto.Message):
    common: "Common" = betterproto.message_field(1)
    count: int = betterproto.uint64_field(2)
    total: int = betterproto.uint64_field(3)
    color: int = betterproto.uint64_field(4)
    user: "User" = betterproto.message_field(5)
    icon: str = betterproto.string_field(6)
    double_like_detail: "DoubleLikeDetail" = betterproto.message_field(7)
    display_style: "DisplayStyle" = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class Common(betterproto.Message):
    method: str = betterproto.string_field(1)
    msg_id: int = betterproto.uint64_field(2)
    room_id: int = betterproto.uint64_field(3)
    create_time: int = betterproto.uint64_field(4)
    monitor: int = betterproto.uint64_field(5)
    show_msg: bool = betterproto.bool_field(6)
    fold_type: bool = betterproto.bool_field(7)
    anchor_fold_type: bool = betterproto.bool_field(8)
    priority_score: int = betterproto.uint64_field(9)


@dataclass(eq=False, repr=False)
class User(betterproto.Message):
    id: int = betterproto.uint64_field(1)
    short_id: int = betterproto.uint64_field(2)
    nick_name: str = betterproto.string_field(3)
    gender: int = betterproto.uint64_field(4)
    signature: str = betterproto.string_field(5)
    level: int = betterproto.uint32_field(6)
    birthday: int = betterproto.uint64_field(7)
    telephone: str = betterproto.string_field(8)
    avatar_thumb: "Image" = betterproto.message_field(9)
    avatar_medium: "Image" = betterproto.message_field(10)
    avatar_large: "Image" = betterproto.message_field(11)
    verified: bool = betterproto.bool_field(12)
    experience: int = betterproto.uint32_field(13)
    city: str = betterproto.string_field(14)
    status: int = betterproto.int32_field(15)
    create_time: int = betterproto.uint64_field(16)
    modify_time: int = betterproto.uint64_field(17)
    secret: int = betterproto.uint32_field(18)
    share_qrcode_uri: str = betterproto.string_field(19)
    income_share_percent: int = betterproto.uint32_field(20)
    badge_image_list: List["Image"] = betterproto.message_field(21)
    border: str = betterproto.string_field(22)
    medel_id: str = betterproto.string_field(23)


@dataclass(eq=False, repr=False)
class Image(betterproto.Message):
    url_list: List[str] = betterproto.string_field(1)
    uri: str = betterproto.string_field(2)
    height: int = betterproto.uint64_field(3)
    width: int = betterproto.uint64_field(4)
    avg_color: str = betterproto.string_field(5)
    image_type: int = betterproto.uint32_field(6)
    open_web_url: str = betterproto.string_field(7)
    content: "Content" = betterproto.message_field(8)
    is_animated: bool = betterproto.bool_field(9)


@dataclass(eq=False, repr=False)
class Content(betterproto.Message):
    name: str = betterproto.string_field(1)
    font_color: str = betterproto.string_field(2)
    level: int = betterproto.uint64_field(3)
    alternative_text: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class TextEffect(betterproto.Message):
    portrait: "TextEffectDetail" = betterproto.message_field(1)
    landscape: "TextEffectDetail" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class TextEffectDetail(betterproto.Message):
    background: "TextFormat" = betterproto.message_field(1)
    text: "TextFormat" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class TextFormat(betterproto.Message):
    color: str = betterproto.string_field(1)
    bold: bool = betterproto.bool_field(2)
    italic: bool = betterproto.bool_field(3)
    weight: int = betterproto.uint32_field(4)
    italic_angle: int = betterproto.uint32_field(5)
    font_size: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class Gift(betterproto.Message):
    id: int = betterproto.uint64_field(1)
    name: str = betterproto.string_field(2)
    describe: str = betterproto.string_field(3)
    type: int = betterproto.uint32_field(4)
    diamond_count: int = betterproto.uint32_field(5)
    duration: int = betterproto.uint32_field(6)
    icon: "Image" = betterproto.message_field(7)
    gift_image: "Image" = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class PublicAreaCommon(betterproto.Message):
    user_label: "UserLabel" = betterproto.message_field(1)
    user_consume_in_room: int = betterproto.uint64_field(2)


@dataclass(eq=False, repr=False)
class UserLabel(betterproto.Message):
    type: int = betterproto.int32_field(1)
    content: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class LandscapeAreaCommon(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class FanTicketInfo(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class Priority(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class BatchInfo(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DoubleLikeDetail(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class DisplayStyle(betterproto.Message):
    pass
